name: Veracode Static Analysis

on:
  push:
    branches: [Vulnerabilidad]

jobs:
  veracode_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package application
        run: zip -r app.zip . -x '*.git*'

      - name: Veracode Upload and Scan
        uses: veracode/veracode-uploadandscan-action@0.2.7

        with:
          appname: 'company-management-app_UNIE'
          createprofile: true
          filepath: 'app.zip'
          version: '${{ github.run_id }}'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY_SECRET }}'
          deleteincompletescan: false
